### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'NAN'. Did you mean: 'nan'?

### ISSUE THREAD

**Issue by swaipdev** [NativeSensors/EyeGestures#28]
I'm running your example code on Windows 11, in a Python virtual environment :

from eyeGestures.utils import VideoCapture
from eyeGestures.eyegestures import EyeGestures_v2

# Initialize gesture engine and video capture
gestures = EyeGestures_v2()
cap = VideoCapture(0)  
calibrate = True
screen_width = 500
screen_height= 500

# Process each frame
while True:
    ret, frame = cap.read()
    event, cevent = gestures.step(frame,
        calibrate,
        screen_width,
        screen_height,
        context="my_context")

    if event:
        cursor_x, cursor_y = event.point[0], event.point[1]
        fixation = event.fixation
        # calibration_radius: radius for data collection during calibration
 
I get stuck here : 

  File "\eyegestures2\venv\lib\site-packages\numpy\__init__.py", line 428, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'NAN'. Did you mean: 'nan'?

Any idea what this could be ?

**Comment by PeterWaIIace** [comment]
Could you tell me what version of numpy are you using? And what operating system you are using as well.

**Comment by swaipdev** [comment]
Hi, 

Windows 11 and numpy 2.1.2

Carlo Giordano
Swaip

***@***.***


On 10/17/2024 11:54:56 AM, W4ltz ***@***.***> wrote:
Could you tell me what version of numpy are you using? And what operating system you are using as well.

**Comment by PeterWaIIace** [comment]
I will try replicate that error later today with that settings! Thanks.

**Comment by PeterWaIIace** [comment]
@swaipdev 

I could not replicate that error yet with `numpy 2.1.2`, but currently in `requirements.txt` we are using `numpy 1`, so I would recommend to downgrade and test against that.
